<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Análisis con datos faltantes | Visualización de Datos con R Sección 3</title>
  <meta name="description" content="Chapter 2 Análisis con datos faltantes | Visualización de Datos con R Sección 3" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Análisis con datos faltantes | Visualización de Datos con R Sección 3" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Análisis con datos faltantes | Visualización de Datos con R Sección 3" />
  
  
  

<meta name="author" content="Lihki Rubio" />


<meta name="date" content="2021-11-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="introducción-a-postgresql-en-r.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>
<link href="libs/vembedr-0.1.4/css/vembedr.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://www.uninorte.edu.co/web/maestria-en-estadistica-aplicada">Maestría en Estadística Aplicada</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Modelo de series de tiempo</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#modelo-arima"><i class="fa fa-check"></i><b>1.1</b> Modelo <code>ARIMA</code></a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#el-proceso-estacionario"><i class="fa fa-check"></i><b>1.2</b> El proceso estacionario</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#transformación-de-una-serie-no-estacionaria-en-una-serie-serie-estacionaria"><i class="fa fa-check"></i><b>1.3</b> Transformación de una serie no estacionaria en una serie serie estacionaria</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#diferenciación-de-series-temporales"><i class="fa fa-check"></i><b>1.4</b> Diferenciación de series temporales</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#transformación-logarítmica"><i class="fa fa-check"></i><b>1.5</b> Transformación logarítmica</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#proceso-arima"><i class="fa fa-check"></i><b>1.6</b> Proceso <code>ARIMA</code></a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#identificación-del-grado-de-diferenciación-del-modelo"><i class="fa fa-check"></i><b>1.7</b> Identificación del grado de diferenciación del modelo</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#predicción-del-consumo-mensual-de-gas-natural-en-ee.uu"><i class="fa fa-check"></i><b>1.8</b> Predicción del consumo mensual de gas natural en EE.UU</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#la-función-auto.arima"><i class="fa fa-check"></i><b>1.9</b> La función <code>auto.arima</code></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html"><i class="fa fa-check"></i><b>2</b> Análisis con datos faltantes</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#introducción"><i class="fa fa-check"></i><b>2.1</b> Introducción</a></li>
<li class="chapter" data-level="2.2" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#visualización-de-los-datos-que-faltan"><i class="fa fa-check"></i><b>2.2</b> Visualización de los datos que faltan</a></li>
<li class="chapter" data-level="2.3" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#tipos-de-datos-faltantes"><i class="fa fa-check"></i><b>2.3</b> Tipos de datos faltantes</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#visualización-de-datos-faltantes"><i class="fa fa-check"></i><b>2.3.1</b> Visualización de datos faltantes</a></li>
<li class="chapter" data-level="2.3.2" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#borrado-de-la-lista"><i class="fa fa-check"></i><b>2.3.2</b> Borrado de la lista</a></li>
<li class="chapter" data-level="2.3.3" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#imputación-de-la-media"><i class="fa fa-check"></i><b>2.3.3</b> Imputación de la media</a></li>
<li class="chapter" data-level="2.3.4" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#otras-técnicas-de-imputación"><i class="fa fa-check"></i><b>2.3.4</b> Otras técnicas de imputación</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#detección-de-valores-atípicos"><i class="fa fa-check"></i><b>2.4</b> Detección de valores atípicos</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#estadísticas-descriptivas"><i class="fa fa-check"></i><b>2.4.1</b> Estadísticas descriptivas</a></li>
<li class="chapter" data-level="2.4.2" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#histogramas"><i class="fa fa-check"></i><b>2.4.2</b> Histogramas</a></li>
<li class="chapter" data-level="2.4.3" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#boxplot"><i class="fa fa-check"></i><b>2.4.3</b> Boxplot</a></li>
<li class="chapter" data-level="2.4.4" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#percentiles"><i class="fa fa-check"></i><b>2.4.4</b> Percentiles</a></li>
<li class="chapter" data-level="2.4.5" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#filtro-de-hampel"><i class="fa fa-check"></i><b>2.4.5</b> Filtro de Hampel</a></li>
<li class="chapter" data-level="2.4.6" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#prueba-de-grubbs"><i class="fa fa-check"></i><b>2.4.6</b> Prueba de Grubbs</a></li>
<li class="chapter" data-level="2.4.7" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#prueba-de-dixon"><i class="fa fa-check"></i><b>2.4.7</b> Prueba de Dixon</a></li>
<li class="chapter" data-level="2.4.8" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#prueba-de-rosner"><i class="fa fa-check"></i><b>2.4.8</b> Prueba de Rosner</a></li>
<li class="chapter" data-level="2.4.9" data-path="análisis-con-datos-faltantes.html"><a href="análisis-con-datos-faltantes.html#tratamiento-de-los-valores-atípicos"><i class="fa fa-check"></i><b>2.4.9</b> Tratamiento de los valores atípicos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introducción-a-postgresql-en-r.html"><a href="introducción-a-postgresql-en-r.html"><i class="fa fa-check"></i><b>3</b> Introducción a PostgreSQL en R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="introducción-a-postgresql-en-r.html"><a href="introducción-a-postgresql-en-r.html#conexión-con-r"><i class="fa fa-check"></i><b>3.1</b> Conexión con R</a></li>
<li class="chapter" data-level="3.2" data-path="introducción-a-postgresql-en-r.html"><a href="introducción-a-postgresql-en-r.html#importación-de-tablas"><i class="fa fa-check"></i><b>3.2</b> Importación de tablas</a></li>
<li class="chapter" data-level="3.3" data-path="introducción-a-postgresql-en-r.html"><a href="introducción-a-postgresql-en-r.html#candlesticks-plot"><i class="fa fa-check"></i><b>3.3</b> Candlesticks plot</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html"><i class="fa fa-check"></i><b>4</b> Visualización con <code>plotly</code> y <code>shiny</code></a>
<ul>
<li class="chapter" data-level="4.1" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#introducción-a-plotly"><i class="fa fa-check"></i><b>4.1</b> Introducción a <code>plotly</code></a></li>
<li class="chapter" data-level="4.2" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#introducción-a-ggplotly"><i class="fa fa-check"></i><b>4.2</b> Introducción a <code>ggplotly</code></a></li>
<li class="chapter" data-level="4.3" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#barras-e-histogramas"><i class="fa fa-check"></i><b>4.3</b> Barras e histogramas</a></li>
<li class="chapter" data-level="4.4" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#boxplots"><i class="fa fa-check"></i><b>4.4</b> Boxplots</a></li>
<li class="chapter" data-level="4.5" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#mapas"><i class="fa fa-check"></i><b>4.5</b> Mapas</a></li>
<li class="chapter" data-level="4.6" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#mapas-integrados"><i class="fa fa-check"></i><b>4.6</b> Mapas integrados</a></li>
<li class="chapter" data-level="4.7" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#mapas-coropléticos"><i class="fa fa-check"></i><b>4.7</b> Mapas coropléticos</a></li>
<li class="chapter" data-level="4.8" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#shiny"><i class="fa fa-check"></i><b>4.8</b> Shiny</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#su-primera-aplicación-shiny"><i class="fa fa-check"></i><b>4.8.1</b> Su primera aplicación Shiny</a></li>
<li class="chapter" data-level="4.8.2" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#ocultación-y-rediseño-al-cambiar-de-tamaño"><i class="fa fa-check"></i><b>4.8.2</b> Ocultación y rediseño al cambiar de tamaño</a></li>
<li class="chapter" data-level="4.8.3" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#eventos-de-alcance"><i class="fa fa-check"></i><b>4.8.3</b> Eventos de alcance</a></li>
<li class="chapter" data-level="4.8.4" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#drill-down"><i class="fa fa-check"></i><b>4.8.4</b> Drill-down</a></li>
<li class="chapter" data-level="4.8.5" data-path="visualización-con-plotly-y-shiny.html"><a href="visualización-con-plotly-y-shiny.html#despliegue-de-aplicación-shiny"><i class="fa fa-check"></i><b>4.8.5</b> Despliegue de aplicación Shiny</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.uninorte.edu.co/" target="blank">Universidad del Norte</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Visualización de Datos con R Sección 3</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análisis-con-datos-faltantes" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Análisis con datos faltantes</h1>
<div id="introducción" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Introducción</h2>
<ul>
<li><p>Los datos faltantes es uno de los temas que se ignoran en la mayoría de los textos introductorios. Probablemente, parte de la razón por la que esto es así es que todavía abundan muchos mitos sobre el análisis con datos ausentes. Además, algunas de las investigaciones sobre técnicas de vanguardia es aún relativamente nueva. Una razón más legítima para su ausencia en los textos introductorios es que la mayoría de las metodologías más de principios son bastante complicadas, desde el punto de vista matemático. Sin embargo, la increíble ubicuidad de los problemas relacionados con los datos faltantes en el análisis de datos de la vida real requiere que se aborde el tema. Esta sección sirve como una suave introducción al tema y a una de las técnicas más eficaces para tratarla. Un refrán común sobre el tema es algo así como que la mejor manera de tratar con los datos que faltan es no tenerlos. Es cierto que los datos que faltan son un tema complicado, y hay muchas maneras de hacerlo mal. Es importante no llevar este consejo al extremo, sin embargo, para eludir los problemas de los datos perdidos, algunos han impedido participantes en una encuesta, que por ejemplo, siguen sin responder a todas las preguntas de un formulario.</p></li>
<li><p>Hay tratamientos para los datos que faltan, pero no hay tratamientos para los datos malos. El tratamiento estándar para el problema de los datos que faltan es reemplazar los datos que faltan por valores no ausentes. Este proceso se denomina imputación. En la mayoría de los casos, el objetivo de la imputación no es recrear el conjunto de datos completo perdido, sino permitir que se realicen estimaciones o inferencias estadísticas válidas a partir de los datos perdidos. Por ello, la eficacia de las diferentes técnicas de imputación no puede evaluarse por su capacidad de recrear los datos con la mayor exactitud posible a partir de un conjunto de datos perdidos simulado, sino que deben juzgarse por su capacidad de apoyar las mismas inferencias estadísticas que se obtendrían del análisis de los datos completos que se extraen del análisis.</p></li>
<li><p>De este modo, rellenar los datos que faltan es sólo un paso hacia el verdadero objetivo: el análisis. El conjunto de datos imputados rara vez se considera el objetivo final de la imputación. En la práctica, hay muchas formas diferentes de tratar los datos que faltan, algunas son buenas y otras no tanto. Algunas están bien en determinadas circunstancias, pero no en otras. Algunas implican la eliminación de datos perdidos, mientras que otras implican la imputación. Vamos a mencionar brevemente algunos de los métodos más comunes. Sin embargo, el objetivo final de esta sección, es iniciarle en lo que a menudo se describe como el estándar de oro de las técnicas de imputación: la imputación múltiple.</p></li>
</ul>
</div>
<div id="visualización-de-los-datos-que-faltan" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Visualización de los datos que faltan</h2>
<ul>
<li>Para demostrar la visualización de patrones de datos ausentes, primero tenemos que crear algunos datos ausentes. Para mostrar cómo utilizar la imputación múltiple en un escenario semirealista, vamos a crear una versión del conjunto de datos <code>mtcars</code> con algunos valores perdidos: Configuremos <code>seed</code> (para la aleatoriedad determinista), y creemos una variable para mantener nuestro nuevo conjunto de datos. Los datos se extrajeron de la revista <strong>Motor Trend US</strong> de 1974 y comprenden el consumo de combustible y 10 aspectos del diseño y el rendimiento de 32 automóviles (modelos de 1973 a 1974).</li>
</ul>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="análisis-con-datos-faltantes.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb35-2"><a href="análisis-con-datos-faltantes.html#cb35-2" aria-hidden="true" tabindex="-1"></a>miss_mtcars <span class="ot">&lt;-</span> mtcars</span></code></pre></div>
<ul>
<li>En primer lugar, vamos a crear siete valores faltantes en <code>drat</code> (alrededor del 20 por ciento), cinco valores faltantes en la columna <code>mpg</code> (alrededor del 15 por ciento), cinco valores faltantes en la columna <code>cyl</code>, tres valores faltantes en <code>wt</code> (alrededor del 10 por ciento), y tres valores faltantes en <code>vs</code></li>
</ul>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="análisis-con-datos-faltantes.html#cb36-1" aria-hidden="true" tabindex="-1"></a>some_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(miss_mtcars), <span class="dv">7</span>)</span>
<span id="cb36-2"><a href="análisis-con-datos-faltantes.html#cb36-2" aria-hidden="true" tabindex="-1"></a>miss_mtcars<span class="sc">$</span>drat[some_rows] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb36-3"><a href="análisis-con-datos-faltantes.html#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="análisis-con-datos-faltantes.html#cb36-4" aria-hidden="true" tabindex="-1"></a>some_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(miss_mtcars), <span class="dv">5</span>)</span>
<span id="cb36-5"><a href="análisis-con-datos-faltantes.html#cb36-5" aria-hidden="true" tabindex="-1"></a>miss_mtcars<span class="sc">$</span>mpg[some_rows] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb36-6"><a href="análisis-con-datos-faltantes.html#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="análisis-con-datos-faltantes.html#cb36-7" aria-hidden="true" tabindex="-1"></a>some_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(miss_mtcars), <span class="dv">5</span>)</span>
<span id="cb36-8"><a href="análisis-con-datos-faltantes.html#cb36-8" aria-hidden="true" tabindex="-1"></a>miss_mtcars<span class="sc">$</span>cyl[some_rows] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb36-9"><a href="análisis-con-datos-faltantes.html#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="análisis-con-datos-faltantes.html#cb36-10" aria-hidden="true" tabindex="-1"></a>some_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(miss_mtcars), <span class="dv">3</span>)</span>
<span id="cb36-11"><a href="análisis-con-datos-faltantes.html#cb36-11" aria-hidden="true" tabindex="-1"></a>miss_mtcars<span class="sc">$</span>wt[some_rows] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb36-12"><a href="análisis-con-datos-faltantes.html#cb36-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-13"><a href="análisis-con-datos-faltantes.html#cb36-13" aria-hidden="true" tabindex="-1"></a>some_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(miss_mtcars), <span class="dv">3</span>)</span>
<span id="cb36-14"><a href="análisis-con-datos-faltantes.html#cb36-14" aria-hidden="true" tabindex="-1"></a>miss_mtcars<span class="sc">$</span>vs[some_rows] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code></pre></div>
<ul>
<li>Ahora, vamos a crear cuatro valores que faltan en <code>qsec</code>, pero sólo para los coches automáticos</li>
</ul>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="análisis-con-datos-faltantes.html#cb37-1" aria-hidden="true" tabindex="-1"></a>only_automatic <span class="ot">&lt;-</span> <span class="fu">which</span>(miss_mtcars<span class="sc">$</span>am<span class="sc">==</span><span class="dv">0</span>)</span>
<span id="cb37-2"><a href="análisis-con-datos-faltantes.html#cb37-2" aria-hidden="true" tabindex="-1"></a>some_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(only_automatic, <span class="dv">4</span>)</span>
<span id="cb37-3"><a href="análisis-con-datos-faltantes.html#cb37-3" aria-hidden="true" tabindex="-1"></a>miss_mtcars<span class="sc">$</span>qsec[some_rows] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code></pre></div>
<p>Ahora, echemos un vistazo al conjunto de datos:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="análisis-con-datos-faltantes.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(miss_mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0  NA  160 110 3.90 2.620 16.46 NA  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8  NA  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105   NA 3.460 20.22  1  0    3    1</code></pre>
<ul>
<li>Ahora vamos a visualizar los datos faltantes. La primera forma en que vamos a visualizar el patrón de los datos faltantes es utilizando la función función <code>md.pattern</code> del paquete <code>mice</code> (que es también el paquete que vamos a utilizar para imputar nuestros datos faltantes). Si no tiene el paquete instálelo antes</li>
</ul>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="análisis-con-datos-faltantes.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb40-2"><a href="análisis-con-datos-faltantes.html#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">md.pattern</span>(miss_mtcars)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-32-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>##    disp hp am gear carb wt vs qsec mpg cyl drat   
## 12    1  1  1    1    1  1  1    1   1   1    1  0
## 6     1  1  1    1    1  1  1    1   1   1    0  1
## 2     1  1  1    1    1  1  1    1   1   0    1  1
## 3     1  1  1    1    1  1  1    1   0   1    1  1
## 1     1  1  1    1    1  1  1    1   0   0    1  2
## 1     1  1  1    1    1  1  1    0   1   1    1  1
## 1     1  1  1    1    1  1  1    0   0   1    1  2
## 1     1  1  1    1    1  1  0    1   1   0    1  2
## 1     1  1  1    1    1  1  0    0   1   1    1  2
## 1     1  1  1    1    1  1  0    0   1   0    1  3
## 2     1  1  1    1    1  0  1    1   1   1    1  1
## 1     1  1  1    1    1  0  1    1   1   1    0  2
##       0  0  0    0    0  3  3    4   5   5    7 27</code></pre>
<ul>
<li><p>Un patrón de datos faltantes por fila se refiere a las columnas que faltan en cada fila. Esta función agrega y cuenta el número de filas con el mismo patrón de datos perdidos. Esta función produce una matriz binaria (0 y 1). Las celdas con un 1 representan datos no faltantes; los 0s representan datos que faltan. Como las filas están ordenadas en un orden creciente de ausencia, la primera fila siempre se refiere al patrón de datos ausentes que contiene la menor cantidad de datos faltantes.</p></li>
<li><p>La columna más a la izquierda es un conteo del número de filas que muestran el patrón de datos faltantes, y la columna más a la derecha es un recuento del número de puntos de datos perdidos en ese patrón. La última fila contiene un recuento del número de puntos de datos que faltan en cada columna. Como puede ver, 12 de las filas no contienen datos perdidos.</p></li>
<li><p>Sólo hay seis filas que contienen más de un valor perdido. Sólo una de estas
filas contiene más de dos valores perdidos (como se muestra en la penúltima fila). En cuanto a los conjuntos de datos con datos faltantes, este en particular no contiene mucho. No es raro que en algunos conjuntos de datos falte más del 30% de los datos. Este conjunto de datos no llega ni al 3%. Ahora vamos a visualizar el patrón de datos faltantes gráficamente utilizando el paquete <code>VIM</code>. Probablemente también tenga que instalarlo.</p></li>
</ul>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="análisis-con-datos-faltantes.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(VIM)</span>
<span id="cb42-2"><a href="análisis-con-datos-faltantes.html#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">aggr</span>(miss_mtcars, <span class="at">numbers=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-33-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="análisis-con-datos-faltantes.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">marginplot</span>(miss_mtcars[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-34-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li><p>A simple vista, esta representación nos muestra, sin esfuerzo, que la columna <code>drat</code> representa la mayor proporción de datos faltantes, por columnas, seguida de <code>mpg, cyl, qsec, vs</code> y <code>wt</code>. El gráfico de la derecha nos muestra información similar a la de la salida de <code>md.pattern</code>. Esta representación, sin embargo, hace que sea más fácil saber si hay algún patrón sistemático de omisión. Las celdas azules representan los datos no ausentes, y las rojas representan los datos que faltan. Los números de la derecha del gráfico representan la proporción de filas que muestran ese patrón de datos perdidos. El 37,5% de las filas no contienen ningún tipo de dato que falte.</p></li>
<li><p>El diagrama de caja rojo de la izquierda muestra la distribución de <code>cyl</code> sin <code>mpg</code>, mientras que el diagrama de caja azul muestra la distribución de los restantes puntos de datos. Lo mismo ocurre con los gráficos de caja de <code>mpg</code> en la parte inferior del gráfico. Si los datos tienen mecanismo <code>MCAR</code> se espera que los gráficos de caja rojos y azules sean muy similares.</p></li>
</ul>
</div>
<div id="tipos-de-datos-faltantes" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Tipos de datos faltantes</h2>
<p>El paquete <code>VIM</code> nos permitió visualizar los patrones de datos que faltaban. Un término relacionado, el mecanismo de datos perdidos, describe el proceso que determina la probabilidad de que cada punto de datos sea faltante. Hay tres categorías principales de mecanismos de datos perdidos: <strong>Missing Completely At Random (MCAR), Missing At Random (MAR)</strong>, y <strong>Missing Not At Random (MNAR)</strong>. La discriminación basada en el mecanismo de datos perdidos es crucial, ya que nos informa sobre las opciones para manejar los datos faltantes.</p>
<ul>
<li><p><strong>Faltantes completamente al azar <code>(MCAR)</code></strong></p>
<ul>
<li>El primer mecanismo, <code>MCAR</code>, se produce cuando la falta de datos no está relacionada con la datos. Esto ocurriría, por ejemplo, si se borraran filas de una base de datos al azar, o si una ráfaga de viento se llevara una muestra aleatoria de los formularios de encuesta de un investigador. El mecanismo que rige la ausencia de <code>drat, mpg, cyl, wt</code>, y <code>vs</code>’ es <code>MCAR</code>, porque seleccionamos al azar los elementos que faltan. Este mecanismo, aunque es el más fácil de trabajar, rara vez es sostenible en la práctica.</li>
</ul></li>
<li><p><strong>Faltantes no aleatorios <code>(MNAR)</code></strong></p>
<ul>
<li>El mecanismo <code>MNAR</code> se produce cuando la ausencia de una variable está relacionada con la variable en sí misma. Por ejemplo, supongamos que la báscula que pesa cada coche tiene una capacidad de sólo 3.700 libras y, por ello, los ocho coches que pesaban más se registraron como <code>NA</code>. Este es un ejemplo clásico del mecanismo <code>MNAR</code>, es el propio peso de la observación la causa de que falte. Otro ejemplo sería si durante el transcurso del ensayo de un fármaco antidepresivo los participantes a los que no les ayudaba el fármaco se deprimían demasiado para continuar con el ensayo. Al final del ensayo, cuando se accede y se registra el nivel de depresión de todos los participantes, habrá valores que falten para los participantes cuyo motivo de ausencia está relacionado con su nivel de depresión.</li>
</ul></li>
<li><p><strong>Faltantes al azar <code>(MAR)</code></strong></p>
<ul>
<li><p>El mecanismo, <code>faltante al azar</code>, tiene un nombre un tanto desafortunado, al contrario de lo que pueda parecer, significa que existe una relación sistemática entre la ausencia de una variable de resultado y otras variables observadas, pero no la variable de resultado en sí misma.</p></li>
<li><p>La mejor manera de explicarlo es con el siguiente ejemplo: Supongamos que en una encuesta hay una pregunta sobre el nivel de ingresos. Debido a ello, un gran número de participantes en la encuesta cuya lengua materna no es el inglés no pudo interpretar la pregunta y la dejaron en blanco. Si la encuesta sólo recogía el nombre, el sexo y los ingresos, el mecanismo de datos faltantes de la pregunta sobre los ingresos sería <code>MNAR</code>. Sin embargo, si el cuestionario incluía una pregunta sobre si el participante hablaba inglés como como primera lengua, el mecanismo sería <code>MAR</code>. La inclusión de la variable <em>Is English</em> significa que la falta de respuesta a la pregunta sobre los ingresos puede puede explicarse por completo. La razón por la que el nombre falta al azar es que cuando se controla la relación entre la variable omitida y la(s) variable(s) observada(s) con la que está relacionada (por ejemplo, ¿Cuál es su renta? y ¿Es el inglés su primera lengua? respectivamente), los datos faltan al azar.</p></li>
<li><p>Como otro ejemplo, existe una relación sistemática entre las variables <code>am</code> y <code>qsec</code> en nuestro conjunto de datos simulados que faltan: los <code>qsecs</code> sólo faltan en los coches automáticos. Pero dentro del grupo de coches automáticos, la variable <code>qsec</code> falta al azar. Por lo tanto, el mecanismo de <code>qsec</code> es <code>MAR</code>; controlando el tipo de transmisión, <code>qsec</code> falta al azar. Tenga en cuenta, sin embargo, que si eliminamos <code>am</code> de nuestro conjunto de datos simulado, <code>qsec</code> se convertiría en <code>MNAR</code>.</p></li>
</ul></li>
<li><p><strong>Observación</strong></p>
<ul>
<li>Quizá haya observado que el lugar que ocupa un conjunto de datos concreto en la taxonomía del mecanismo de datos perdidos depende de las variables que incluye. Por ejemplo, sabemos que el mecanismo detrás de <code>qsec</code> es <code>MAR</code>, pero si el conjunto de datos no incluyera <code>am</code>, sería <code>MNAR</code>. Como somos nosotros los que creamos los datos, sabemos el procedimiento que dio lugar a los valores perdidos de <code>qsec</code>. Si no fuéramos nosotros los que creamos los datos, como ocurre en el mundo real, y el conjunto de datos no contuviera la columna <code>am</code> simplemente veríamos una cantidad de valores <code>qsec</code> que faltan arbitrariamente. Esto podría llevarnos a creer que los datos son <code>MCAR</code>. Sin embargo, no lo es; sólo porque la variable con la cual otra variable faltante está sistemáticamente relacionada no se observa, no quiere decir que esta no exista. Esto plantea una cuestión crítica: ¿podemos estar seguros de que nuestros datos no son <code>MCAR</code>? La respuesta desafortunada es no. Dado que los datos que necesitamos para demostrar o refutar el <code>MNAR</code> faltan <em>ipso facto</em>, la suposición de <code>MNAR</code> nunca puede ser desconfirmada de forma concluyente. Es nuestro trabajo, como analistas de datos con pensamiento crítico, preguntar si es probable que haya un mecanismo <code>MNAR</code> o no.</li>
</ul></li>
</ul>
<div id="visualización-de-datos-faltantes" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Visualización de datos faltantes</h3>
<ul>
<li><p>Tomando el conjunto de datos <code>airquality</code>, un conjunto de datos de mediciones diarias de la calidad del aire en Nueva York de mayo a septiembre de 1973, que tiene valores <code>NA</code> dentro de sus variables. Las filas del conjunto de datos representan 154 días consecutivos. Cualquier eliminación de estas filas afectará a la continuidad del tiempo, lo que puede <em>afectar a cualquier análisis de series temporales que se realice</em>. Veamos con más detalle el conjunto de datos de la calidad del aire</p></li>
<li><p>Iniciamos visualizando los datos faltantes. Eliminaremos algunos puntos de datos del conjunto de datos para este ejemplo. En lo que respecta a las variables categóricas, la sustitución de las mismas no suele ser aconsejable. Algunas prácticas comunes incluyen la sustitución de las variables categóricas que faltan por la moda de las observadas, sin embargo, es cuestionable si es una buena opción. Aunque en este caso no faltan puntos de datos de las variables categóricas, las eliminamos de nuestro conjunto de datos (podemos volver a añadirlas más tarde si es necesario) y echamos un vistazo a los datos utilizando <code>summary()</code></p></li>
</ul>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="análisis-con-datos-faltantes.html#cb44-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> airquality</span>
<span id="cb44-2"><a href="análisis-con-datos-faltantes.html#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day
## 1    41     190  7.4   67     5   1
## 2    36     118  8.0   72     5   2
## 3    12     149 12.6   74     5   3
## 4    18     313 11.5   62     5   4
## 5    NA      NA 14.3   56     5   5
## 6    28      NA 14.9   66     5   6</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="análisis-con-datos-faltantes.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data &lt;- airquality</span></span>
<span id="cb46-2"><a href="análisis-con-datos-faltantes.html#cb46-2" aria-hidden="true" tabindex="-1"></a>data[<span class="dv">4</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">7</span>)</span>
<span id="cb46-3"><a href="análisis-con-datos-faltantes.html#cb46-3" aria-hidden="true" tabindex="-1"></a>data[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code></pre></div>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="análisis-con-datos-faltantes.html#cb47-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">6</span>)]</span>
<span id="cb47-2"><a href="análisis-con-datos-faltantes.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code></pre></div>
<pre><code>##      Ozone           Solar.R           Wind             Temp      
##  Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :57.00  
##  1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:73.00  
##  Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  
##  Mean   : 42.13   Mean   :185.9   Mean   : 9.806   Mean   :78.28  
##  3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  
##  Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  
##  NA&#39;s   :37       NA&#39;s   :7       NA&#39;s   :7        NA&#39;s   :5</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="análisis-con-datos-faltantes.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp
## 1    41     190  7.4   NA
## 2    36     118  8.0   NA
## 3    12     149 12.6   NA
## 4    18     313   NA   NA
## 5    NA      NA   NA   NA
## 6    28      NA   NA   66</code></pre>
<ul>
<li>Al parecer, el <code>Ozone</code> es la variable con más puntos de datos perdidos. A continuación vamos a profundizar en los patrones de datos que faltan. Suponiendo que los datos sean <code>MCAR</code>, demasiados datos perdidos también pueden ser un problema. Por lo general, un umbral máximo seguro es el 5% del total para conjuntos de datos grandes. Si los datos que faltan para una determinada característica o muestra son superiores al 5%, probablemente deba dejar de lado esa característica o muestra. Por lo tanto, comprobamos las características (columnas) y las muestras (filas) en las que falta más del 5% de los datos mediante una sencilla función</li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="análisis-con-datos-faltantes.html#cb51-1" aria-hidden="true" tabindex="-1"></a>pMiss <span class="ot">&lt;-</span> <span class="cf">function</span>(x){<span class="fu">sum</span>(<span class="fu">is.na</span>(x))<span class="sc">/</span><span class="fu">length</span>(x)<span class="sc">*</span><span class="dv">100</span>}</span>
<span id="cb51-2"><a href="análisis-con-datos-faltantes.html#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(data,<span class="dv">2</span>,pMiss)</span></code></pre></div>
<pre><code>##     Ozone   Solar.R      Wind      Temp 
## 24.183007  4.575163  4.575163  3.267974</code></pre>
<ul>
<li><p>Vemos que al ozono le falta casi el 25% de los puntos de datos, por lo que podríamos considerar la posibilidad de eliminarlo del análisis o de reunir más mediciones. Las demás variables están por debajo del umbral del 5%, por lo que podemos mantenerlas.</p></li>
<li><p>Usemos <code>md.pattern()</code> para conocer mejor el patrón de los datos que faltan</p></li>
</ul>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="análisis-con-datos-faltantes.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb53-2"><a href="análisis-con-datos-faltantes.html#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">md.pattern</span>(data, <span class="at">rotate.names =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-40-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>##     Temp Solar.R Wind Ozone   
## 104    1       1    1     1  0
## 34     1       1    1     0  1
## 3      1       1    0     1  1
## 1      1       1    0     0  2
## 4      1       0    1     1  1
## 1      1       0    1     0  2
## 1      1       0    0     1  2
## 3      0       1    1     1  1
## 1      0       1    0     1  2
## 1      0       0    0     0  4
##        5       7    7    37 56</code></pre>
<ul>
<li>La salida nos dice que 104 muestras están completas, que a 34 muestras les falta sólo la medición de <code>Ozone</code>, que a 4 muestras les falta sólo el valor de <code>Solar.R</code> y así sucesivamente. Una representación visual quizás más útil puede obtenerse utilizando el paquete <code>VIM</code> de la siguiente manera</li>
</ul>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="análisis-con-datos-faltantes.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(VIM)</span>
<span id="cb55-2"><a href="análisis-con-datos-faltantes.html#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="análisis-con-datos-faltantes.html#cb55-3" aria-hidden="true" tabindex="-1"></a>aggr_plot <span class="ot">&lt;-</span> <span class="fu">aggr</span>(data, <span class="at">col=</span><span class="fu">c</span>(<span class="st">&#39;navyblue&#39;</span>,<span class="st">&#39;red&#39;</span>), <span class="at">numbers=</span><span class="cn">TRUE</span>, <span class="at">sortVars=</span><span class="cn">TRUE</span>, <span class="at">labels=</span><span class="fu">names</span>(data),</span>
<span id="cb55-4"><a href="análisis-con-datos-faltantes.html#cb55-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">cex.axis=</span>.<span class="dv">7</span>, <span class="at">gap=</span><span class="dv">3</span>, <span class="at">ylab=</span><span class="fu">c</span>(<span class="st">&quot;Histogram of missing data&quot;</span>,<span class="st">&quot;Pattern&quot;</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-41-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Variables sorted by number of missings: 
##  Variable      Count
##     Ozone 0.24183007
##   Solar.R 0.04575163
##      Wind 0.04575163
##      Temp 0.03267974</code></pre>
<ul>
<li>El gráfico nos ayuda a entender que a casi el 70% de las muestras no les falta ninguna información, al 22% le falta el valor de <code>Ozono</code> y las restantes muestran otros patrones de ausencia. A través de este enfoque, la situación parece un poco más clara. Otra aproximación visual (esperemos) útil es un gráfico de caja especial</li>
</ul>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="análisis-con-datos-faltantes.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">marginplot</span>(data[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-42-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li>Obviamente, aquí estamos limitados a trazar sólo 2 variables a la vez, pero sin embargo podemos obtener algunas ideas interesantes. El diagrama de caja rojo de la izquierda muestra la distribución de <code>Solar.R</code> sin <code>Ozono</code>, mientras que el diagrama de caja azul muestra la distribución de los restantes puntos de datos. Lo mismo ocurre con los gráficos de caja de <code>Ozono</code> en la parte inferior del gráfico. Si nuestra suposición de los datos <code>MCAR</code> es correcta, entonces esperamos que los gráficos de caja rojos y azules sean muy similares.</li>
</ul>
</div>
<div id="borrado-de-la-lista" class="section level3" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Borrado de la lista</h3>
<ul>
<li><p>El método más utilizado por los científicos de datos para tratar los datos que faltan es simplemente omitir los casos con datos que faltan, analizando únicamente el resto del conjunto de datos. Este método se conoce como eliminación por lista o análisis de casos completos. La función <code>na.omit()</code> en <code>R</code> elimina todos los casos con uno o más valores de datos perdidos en un conjunto de datos.</p></li>
<li><p>La mayor ventaja de este método es su comodidad. Sin embargo, si la naturaleza de los datos es <code>MCAR</code>, la eliminación de la lista dará lugar a errores estándar que son significativos para los datos reducidos, pero no para todo el conjunto de datos, que tenía los datos que faltaban. Este método de tratar los datos que faltan es posiblemente un desperdicio. Si se eliminan los casos de esta manera, hay que ser consciente de la disminución de la capacidad para detectar el verdadero efecto de las variables de interés.</p></li>
<li><p>Sin embargo, si los datos no son <code>MCAR</code>, el análisis de casos completos puede influir mucho en las estimaciones de la media, los coeficientes de regresión y las correlaciones. La supresión de la lista puede causar submuestras sin sentido.</p></li>
<li><p>A continuación, realizamos una simple función <code>na.omit()</code> para eliminar los casos que tienen <code>NAs</code>. Vemos que todas las filas que contenían algún <code>NA</code> en cualquier variable son eliminadas del dataframe</p></li>
</ul>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="análisis-con-datos-faltantes.html#cb58-1" aria-hidden="true" tabindex="-1"></a>airquality_omit <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data)</span>
<span id="cb58-2"><a href="análisis-con-datos-faltantes.html#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airquality_omit)</span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp
## 12    16     256  9.7   69
## 13    11     290  9.2   66
## 14    14     274 10.9   68
## 15    18      65 13.2   58
## 16    14     334 11.5   64
## 17    34     307 12.0   66</code></pre>
<ul>
<li>Dibujemos los histogramas antes y después de la imputación usando <code>ggplot</code></li>
</ul>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="análisis-con-datos-faltantes.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb60-2"><a href="análisis-con-datos-faltantes.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb60-3"><a href="análisis-con-datos-faltantes.html#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hrbrthemes)</span>
<span id="cb60-4"><a href="análisis-con-datos-faltantes.html#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code></pre></div>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="análisis-con-datos-faltantes.html#cb61-1" aria-hidden="true" tabindex="-1"></a>ggp1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">value=</span>data<span class="sc">$</span>Ozone), <span class="fu">aes</span>(<span class="at">x=</span>value)) <span class="sc">+</span></span>
<span id="cb61-2"><a href="análisis-con-datos-faltantes.html#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">&quot;#FBD000&quot;</span>, <span class="at">color=</span><span class="st">&quot;#E52521&quot;</span>, <span class="at">alpha=</span><span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb61-3"><a href="análisis-con-datos-faltantes.html#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Original data&quot;</span>) <span class="sc">+</span></span>
<span id="cb61-4"><a href="análisis-con-datos-faltantes.html#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&#39;Ozone&#39;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&#39;Frequency&#39;</span>) <span class="sc">+</span></span>
<span id="cb61-5"><a href="análisis-con-datos-faltantes.html#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_ipsum</span>() <span class="sc">+</span></span>
<span id="cb61-6"><a href="análisis-con-datos-faltantes.html#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">15</span>))</span>
<span id="cb61-7"><a href="análisis-con-datos-faltantes.html#cb61-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-8"><a href="análisis-con-datos-faltantes.html#cb61-8" aria-hidden="true" tabindex="-1"></a>ggp2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">value=</span>airquality_omit<span class="sc">$</span>Ozone), <span class="fu">aes</span>(<span class="at">x=</span>value)) <span class="sc">+</span></span>
<span id="cb61-9"><a href="análisis-con-datos-faltantes.html#cb61-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">&quot;#43B047&quot;</span>, <span class="at">color=</span><span class="st">&quot;#049CD8&quot;</span>, <span class="at">alpha=</span><span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb61-10"><a href="análisis-con-datos-faltantes.html#cb61-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Listwise Deletion&quot;</span>) <span class="sc">+</span></span>
<span id="cb61-11"><a href="análisis-con-datos-faltantes.html#cb61-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&#39;Ozone&#39;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&#39;Frequency&#39;</span>) <span class="sc">+</span></span>
<span id="cb61-12"><a href="análisis-con-datos-faltantes.html#cb61-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_ipsum</span>() <span class="sc">+</span></span>
<span id="cb61-13"><a href="análisis-con-datos-faltantes.html#cb61-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">15</span>))</span>
<span id="cb61-14"><a href="análisis-con-datos-faltantes.html#cb61-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-15"><a href="análisis-con-datos-faltantes.html#cb61-15" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(ggp1, ggp2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-45-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="imputación-de-la-media" class="section level3" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Imputación de la media</h3>
<ul>
<li><p>Algunos científicos de datos o estadísticos pueden buscar una solución rápida sustituyendo los datos que faltan por la media. La media se utiliza a menudo para imputar datos no categóricos. Por ejemplo, en el conjunto de datos de calidad del aire, supongamos que queremos imputar la media de sus valores perdidos. En este caso, utilizamos el paquete <code>R</code> <code>mice</code>. Cambiando el argumento <code>method = mean</code>, se especifica la imputación de la media, el argumento <code>m = 1</code> cambia las iteraciones a 1, lo que significa no (iteración).</p></li>
<li><p>El fundamento teórico de utilizar la media para imputar los datos perdidos es que la media es una buena estimación para seleccionar aleatoriamente una observación de una distribución normal. Ahora, intentaremos imputar la media para las variables <code>Ozono</code> y <code>Solar.R</code> del conjunto de datos <code>airquality</code>. En primer lugar, vamos a cargar los paquetes <code>mice</code> y <code>mipackages</code> (instale el paquete de <code>CRAN</code> primero usando <code>install.packages("mice")</code> y <code>install.packages("mi")</code>). Para mas información sobre el paquete utlizado visitar <a href="https://cran.r-project.org/web/packages/mice/mice.pdf" class="uri">https://cran.r-project.org/web/packages/mice/mice.pdf</a>. Podemos recuperar el conjunto de datos completo utilizando la función <code>complete()</code>.</p></li>
</ul>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="análisis-con-datos-faltantes.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb62-2"><a href="análisis-con-datos-faltantes.html#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(foreign)</span></code></pre></div>
<ul>
<li>La media de las variables <code>Ozono</code> y <code>Solar.R</code> puede ser imputada por la función <code>mice()</code>.</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="análisis-con-datos-faltantes.html#cb63-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(data, <span class="at">m=</span><span class="dv">5</span>, <span class="at">maxit=</span><span class="dv">50</span>, <span class="at">method =</span><span class="st">&#39;pmm&#39;</span>, <span class="at">seed=</span><span class="dv">500</span>, <span class="at">printFlag =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<ul>
<li>Donde <code>m=5</code> se refiere al número de imputaciones múltiples. El valor por defecto es <code>m=5</code>. <code>meth='pmm'</code> se refiere al método de imputación. En este caso, utilizamos el método de imputación de coincidencia de medias predictivas. Se pueden utilizar otros métodos de imputación, escriba <code>methods(mice)</code> para obtener una lista de los métodos de imputación disponibles.</li>
</ul>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="análisis-con-datos-faltantes.html#cb64-1" aria-hidden="true" tabindex="-1"></a>imp_df <span class="ot">&lt;-</span> <span class="fu">complete</span>(imp)</span>
<span id="cb64-2"><a href="análisis-con-datos-faltantes.html#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(imp_df)</span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp
## 1    41     190  7.4   87
## 2    36     118  8.0   80
## 3    12     149 12.6   74
## 4    18     313 10.9   66
## 5    13      81 16.6   57
## 6    28      78  7.4   66</code></pre>
<ul>
<li>Veamos un histograma y un diagrama de dispersión del aspecto del conjunto de datos de la calidad del aire tras la imputación de la media</li>
</ul>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="análisis-con-datos-faltantes.html#cb66-1" aria-hidden="true" tabindex="-1"></a>ggp1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">value=</span>data<span class="sc">$</span>Ozone), <span class="fu">aes</span>(<span class="at">x=</span>value)) <span class="sc">+</span></span>
<span id="cb66-2"><a href="análisis-con-datos-faltantes.html#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">&quot;#FBD000&quot;</span>, <span class="at">color=</span><span class="st">&quot;#E52521&quot;</span>, <span class="at">alpha=</span><span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb66-3"><a href="análisis-con-datos-faltantes.html#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Original data&quot;</span>) <span class="sc">+</span></span>
<span id="cb66-4"><a href="análisis-con-datos-faltantes.html#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&#39;Ozone&#39;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&#39;Frequency&#39;</span>) <span class="sc">+</span></span>
<span id="cb66-5"><a href="análisis-con-datos-faltantes.html#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_ipsum</span>() <span class="sc">+</span></span>
<span id="cb66-6"><a href="análisis-con-datos-faltantes.html#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">15</span>))</span>
<span id="cb66-7"><a href="análisis-con-datos-faltantes.html#cb66-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-8"><a href="análisis-con-datos-faltantes.html#cb66-8" aria-hidden="true" tabindex="-1"></a>ggp2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">value=</span>imp_df<span class="sc">$</span>Ozone), <span class="fu">aes</span>(<span class="at">x=</span>value)) <span class="sc">+</span></span>
<span id="cb66-9"><a href="análisis-con-datos-faltantes.html#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">&quot;#43B047&quot;</span>, <span class="at">color=</span><span class="st">&quot;#049CD8&quot;</span>, <span class="at">alpha=</span><span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb66-10"><a href="análisis-con-datos-faltantes.html#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mean imputation&quot;</span>) <span class="sc">+</span></span>
<span id="cb66-11"><a href="análisis-con-datos-faltantes.html#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&#39;Ozone&#39;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&#39;Frequency&#39;</span>) <span class="sc">+</span></span>
<span id="cb66-12"><a href="análisis-con-datos-faltantes.html#cb66-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_ipsum</span>() <span class="sc">+</span></span>
<span id="cb66-13"><a href="análisis-con-datos-faltantes.html#cb66-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">15</span>))</span>
<span id="cb66-14"><a href="análisis-con-datos-faltantes.html#cb66-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-15"><a href="análisis-con-datos-faltantes.html#cb66-15" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(ggp1, ggp2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-49-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li>Vamos a comparar las distribuciones de los datos originales e imputados utilizando algunos gráficos útiles. En primer lugar, podemos utilizar un gráfico de dispersión y comparar <code>Ozone</code> con todas las demás variables</li>
</ul>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="análisis-con-datos-faltantes.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb67-2"><a href="análisis-con-datos-faltantes.html#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(imp, Ozone <span class="sc">~</span> Wind <span class="sc">+</span> Temp <span class="sc">+</span> Solar.R, <span class="at">pch=</span><span class="dv">18</span>, <span class="at">cex=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-50-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li>Lo que queremos ver es que la forma de los puntos (imputados) coincida con la de los azules (observados). La coincidencia de la forma nos indica que los valores imputados son realmente <em>valores plausibles</em>. Otro gráfico útil es el de la densidad:</li>
</ul>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="análisis-con-datos-faltantes.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">densityplot</span>(imp)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-51-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li><p>La densidad de los datos imputados para cada conjunto de datos imputados se muestra en color magenta, mientras que la densidad de los datos observados se muestra en azul. De nuevo, según nuestros supuestos anteriores, esperamos que las distribuciones sean similares.</p></li>
<li><p>Es muy recomendable comprobar visualmente la convergencia. Lo comprobamos cuando llamamos a la función de trazado en la variable a la que asignamos la salida de <code>mice</code>, para mostrar gráficos de seguimiento de la media y desviación estándar de todas las variables implicadas en las imputaciones.</p></li>
</ul>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="análisis-con-datos-faltantes.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(imp)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-52-1.png" width="672" style="display: block; margin: auto;" /><img src="_main_files/figure-html/unnamed-chunk-52-2.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li>Cada línea es una de las <code>m</code> imputaciones. Como se puede ver en el gráfico de trazado anterior sobre <code>imp</code>, no hay tendencias claras y las variables se superponen de una iteración a la siguiente. Dicho de otro modo, la varianza dentro de una cadena (hay <code>m</code> cadenas) debería ser aproximadamente igual a la varianza entre las cadenas. Esto indica que se ha logrado la convergencia. Si no se logra la convergencia, se puede aumentar el número de iteraciones que <code>mice</code> emplea especificando explícitamente el parámetro <code>maxit</code> a la función <code>mice</code>. Los siguientes son ejemplos de no convergencia usando el alogritmo <code>mice</code></li>
</ul>
<p><img src="figures/imputation1.png" />
<img src="figures/imputation2.png" /></p>
</div>
<div id="otras-técnicas-de-imputación" class="section level3" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> Otras técnicas de imputación</h3>
<ul>
<li>La función <code>mice</code> entrega distintos métodos de imputación los cuales puede estudiar y aplicar, de acuerdo a lo que requieran sus datos. Puede aplicar la <code>imputación por regresión</code> en R con la configuración del método <code>method = "norm.predict"</code> en la función <code>mice</code>. Puede aplicar la imputación de <code>regresión estocástica</code> en <code>R</code> con la función <code>mice</code> utilizando el método <code>method = "norm.nob"</code>. El paquete <code>mice</code> también incluye un procedimiento de imputación de regresión estocástica bayesiana. Puede aplicar este procedimiento de imputación con la función <code>mice</code> y utilizar como método <code>method = "norm"</code>. Para estos métodos debe seleccionar primero dos columna del conjunto de datos de interes para ajustar constantes del modelo.</li>
</ul>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="análisis-con-datos-faltantes.html#cb70-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data[, <span class="fu">c</span>(<span class="st">&quot;Solar.R&quot;</span>, <span class="st">&quot;Wind&quot;</span>)]</span>
<span id="cb70-2"><a href="análisis-con-datos-faltantes.html#cb70-2" aria-hidden="true" tabindex="-1"></a>imp.regress <span class="ot">&lt;-</span> <span class="fu">mice</span>(data, <span class="at">method=</span><span class="st">&quot;norm.predict&quot;</span>, <span class="at">m=</span><span class="dv">1</span>, <span class="at">maxit=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
##  iter imp variable
##   1   1  Solar.R  Wind</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="análisis-con-datos-faltantes.html#cb72-1" aria-hidden="true" tabindex="-1"></a>imp.regress<span class="sc">$</span>imp<span class="sc">$</span>Wind</span></code></pre></div>
<pre><code>##           1
## 4  9.736111
## 5  9.806622
## 6  9.805925
## 7  9.743832
## 8  9.854140
## 9  9.898263
## 10 9.801744</code></pre>
<ul>
<li>En la actualidad, hay un número limitado de análisis que pueden ser automáticamente agrupados por <code>mice</code> el más importante es el de <code>lm/glm</code>. Sin embargo, si se recuerda, el modelo lineal generalizado es extremadamente flexible, y puede utilizarse para expresar una amplia gama de análisis diferentes. Por extensión, podríamos utilizar la imputación múltiple no sólo para regresión lineal, sino para la regresión logística, la regresión de Poisson, las pruebas <span class="math inline">\(t\)</span>, el <code>ANOVA</code>
<code>ANCOVA</code>, etc. Cada una de estas temáticas pueden ser abordadas como proyectos en este curso.</li>
</ul>
</div>
</div>
<div id="detección-de-valores-atípicos" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Detección de valores atípicos</h2>
<ul>
<li><p>Un valor atípico es un valor o una observación que se aleja de otras observaciones, es decir, un punto de datos que difiere significativamente de otros puntos de datos. <em>Enderlein (1987)</em> va incluso más allá, ya que el autor considera que los valores atípicos son aquellos que se desvían tanto de otras observaciones que se podría suponer un mecanismo de muestreo subyacente diferente.</p></li>
<li><p>Una observación debe compararse siempre con otras observaciones realizadas sobre el mismo fenómeno antes de calificarla realmente de atípica. En efecto, una persona de 200 cm de altura (1,90 m en EE.UU.) se considerará probablemente un valor atípico en comparación con la población general, pero esa misma persona podría no considerarse un valor atípico si midiéramos la altura de los jugadores de baloncesto.</p></li>
<li><p>En esta sección, presentamos varios enfoques para detectar valores atípicos en <code>R</code>, desde técnicas sencillas como la estadística descriptiva (que incluye el mínimo, el máximo, el histograma, el boxplot y los percentiles) hasta técnicas más formales como el filtro de <code>Hampel</code>, el <code>Grubbs</code>, el <code>Dixon</code> y las pruebas de <code>Rosner</code> para detectar valores atípicos. Algunas pruebas estadísticas exigen la ausencia de valores atípicos para sacar conclusiones sólidas, pero la eliminación de valores atípicos no se recomienda en todos los casos y debe hacerse con precaución.</p></li>
</ul>
<div id="estadísticas-descriptivas" class="section level3" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Estadísticas descriptivas</h3>
<ul>
<li>El primer paso para detectar los valores atípicos en <code>R</code> es comenzar con algunas estadísticas descriptivas, y en particular con el mínimo y el máximo. En <code>R</code>, esto se puede hacer fácilmente con la función <code>summary()</code></li>
</ul>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="análisis-con-datos-faltantes.html#cb74-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> ggplot2<span class="sc">::</span>mpg</span>
<span id="cb74-2"><a href="análisis-con-datos-faltantes.html#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 11
##   manufacturer model displ  year   cyl trans      drv     cty   hwy fl    class 
##   &lt;chr&gt;        &lt;chr&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;      &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 audi         a4      1.8  1999     4 auto(l5)   f        18    29 p     compa~
## 2 audi         a4      1.8  1999     4 manual(m5) f        21    29 p     compa~
## 3 audi         a4      2    2008     4 manual(m6) f        20    31 p     compa~
## 4 audi         a4      2    2008     4 auto(av)   f        21    30 p     compa~
## 5 audi         a4      2.8  1999     6 auto(l5)   f        16    26 p     compa~
## 6 audi         a4      2.8  1999     6 manual(m5) f        18    26 p     compa~</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="análisis-con-datos-faltantes.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dat<span class="sc">$</span>hwy)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   12.00   18.00   24.00   23.44   27.00   44.00</code></pre>
<ul>
<li>Nótese que el mínimo y el máximo son, respectivamente, el primer y el último valor de la salida anterior. Como alternativa, también pueden calcularse con las funciones <code>min()</code> y <code>max()</code></li>
</ul>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="análisis-con-datos-faltantes.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(dat<span class="sc">$</span>hwy)</span></code></pre></div>
<pre><code>## [1] 12</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="análisis-con-datos-faltantes.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(dat<span class="sc">$</span>hwy)</span></code></pre></div>
<pre><code>## [1] 44</code></pre>
<ul>
<li>Un claro error de codificación, como un peso de 786 kg (1733 libras) para un humano, ya se detectará fácilmente con esta técnica tan sencilla.</li>
</ul>
</div>
<div id="histogramas" class="section level3" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Histogramas</h3>
<ul>
<li>Otra forma básica de detectar valores atípicos es dibujar un histograma de los datos. Utilizando la base de <code>R</code> (con el número de <code>bins</code> correspondiente a la raíz cuadrada del número de observaciones para tener más <code>bins</code> que la opción por defecto), o usando <code>ggplot2</code>. Considere la columna <code>hwy: highway mileage</code> (<em>miles per gallon</em>)</li>
</ul>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="análisis-con-datos-faltantes.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dat<span class="sc">$</span>hwy,</span>
<span id="cb82-2"><a href="análisis-con-datos-faltantes.html#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">&quot;hwy&quot;</span>,</span>
<span id="cb82-3"><a href="análisis-con-datos-faltantes.html#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">&quot;Histogram of hwy&quot;</span>,</span>
<span id="cb82-4"><a href="análisis-con-datos-faltantes.html#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(dat))</span>
<span id="cb82-5"><a href="análisis-con-datos-faltantes.html#cb82-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-58-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="análisis-con-datos-faltantes.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb83-2"><a href="análisis-con-datos-faltantes.html#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="análisis-con-datos-faltantes.html#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat) <span class="sc">+</span></span>
<span id="cb83-4"><a href="análisis-con-datos-faltantes.html#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> hwy) <span class="sc">+</span></span>
<span id="cb83-5"><a href="análisis-con-datos-faltantes.html#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> 30L, <span class="at">fill =</span> <span class="st">&quot;#0c4c8a&quot;</span>) <span class="sc">+</span></span>
<span id="cb83-6"><a href="análisis-con-datos-faltantes.html#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-59-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li>Según el histograma, parece que hay un par de observaciones más altas que todas las demás</li>
</ul>
</div>
<div id="boxplot" class="section level3" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Boxplot</h3>
<ul>
<li>Además de los histogramas, los <code>boxplots</code> también son útiles para detectar posibles valores atípicos. Considere nuevamente a manera de ejemplo la columna <code>hwy</code></li>
</ul>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="análisis-con-datos-faltantes.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dat<span class="sc">$</span>hwy,</span>
<span id="cb84-2"><a href="análisis-con-datos-faltantes.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">&quot;hwy&quot;</span></span>
<span id="cb84-3"><a href="análisis-con-datos-faltantes.html#cb84-3" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-60-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="análisis-con-datos-faltantes.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat) <span class="sc">+</span></span>
<span id="cb85-2"><a href="análisis-con-datos-faltantes.html#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> hwy) <span class="sc">+</span></span>
<span id="cb85-3"><a href="análisis-con-datos-faltantes.html#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#0c4c8a&quot;</span>) <span class="sc">+</span></span>
<span id="cb85-4"><a href="análisis-con-datos-faltantes.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-61-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li><p>Un diagrama de caja ayuda a visualizar una variable cuantitativa mostrando cinco resúmenes de localización comunes (mínimo, mediana, primer y tercer cuartil y máximo) y cualquier observación que se haya clasificado como presunto valor atípico utilizando el criterio del rango intercuartílico <code>(IQR)</code>.</p></li>
<li><p>Las observaciones consideradas como posibles valores atípicos según el criterio <code>IQR</code> se muestran como puntos en el diagrama de caja. Según este criterio, hay 2 valores atípicos potenciales (véanse los 2 puntos por encima de la línea vertical, en la parte superior del <code>boxplot</code>).</p></li>
<li><p>Recuerde que no por el hecho de que una observación sea considerada como un valor atípico potencial por el criterio IQR debe eliminarla. Eliminar o mantener un valor atípico depende de (i) el contexto de su análisis, (ii) si las pruebas que va a realizar en el conjunto de datos son robustas a los valores atípicos o no, y (iii) a qué distancia está el valor atípico de otras observaciones.</p></li>
<li><p>También es posible extraer los valores de los posibles valores atípicos basándose en el criterio <code>IQR</code> gracias a la función <code>boxplot.stats()$out</code>:</p></li>
</ul>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="análisis-con-datos-faltantes.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot.stats</span>(dat<span class="sc">$</span>hwy)<span class="sc">$</span>out</span></code></pre></div>
<pre><code>## [1] 44 44 41</code></pre>
<ul>
<li>Como puede ver, en realidad hay 3 puntos considerados como posibles valores atípicos: 2 observaciones con un valor de 44 y 1 observación con un valor de 41. Gracias a la función <code>which()</code> es posible extraer el número de fila correspondiente a estos valores atípicos:</li>
</ul>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="análisis-con-datos-faltantes.html#cb88-1" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">boxplot.stats</span>(dat<span class="sc">$</span>hwy)<span class="sc">$</span>out</span>
<span id="cb88-2"><a href="análisis-con-datos-faltantes.html#cb88-2" aria-hidden="true" tabindex="-1"></a>out_ind <span class="ot">&lt;-</span> <span class="fu">which</span>(dat<span class="sc">$</span>hwy <span class="sc">%in%</span> <span class="fu">c</span>(out))</span>
<span id="cb88-3"><a href="análisis-con-datos-faltantes.html#cb88-3" aria-hidden="true" tabindex="-1"></a>out_ind</span></code></pre></div>
<pre><code>## [1] 213 222 223</code></pre>
<ul>
<li>Con esta información, ahora puede volver fácilmente a las filas específicas del conjunto de datos para verificarlas, o imprimir todas las variables para estos valores atípicos:</li>
</ul>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="análisis-con-datos-faltantes.html#cb90-1" aria-hidden="true" tabindex="-1"></a>dat[out_ind, ]</span></code></pre></div>
<pre><code>## # A tibble: 3 x 11
##   manufacturer model      displ  year   cyl trans  drv     cty   hwy fl    class
##   &lt;chr&gt;        &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt;
## 1 volkswagen   jetta        1.9  1999     4 manua~ f        33    44 d     comp~
## 2 volkswagen   new beetle   1.9  1999     4 manua~ f        35    44 d     subc~
## 3 volkswagen   new beetle   1.9  1999     4 auto(~ f        29    41 d     subc~</code></pre>
<ul>
<li>También es posible imprimir los valores de los valores atípicos directamente en el boxplot con la función <code>mtext()</code></li>
</ul>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="análisis-con-datos-faltantes.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dat<span class="sc">$</span>hwy,</span>
<span id="cb92-2"><a href="análisis-con-datos-faltantes.html#cb92-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;hwy&quot;</span>,</span>
<span id="cb92-3"><a href="análisis-con-datos-faltantes.html#cb92-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Boxplot of highway miles per gallon&quot;</span></span>
<span id="cb92-4"><a href="análisis-con-datos-faltantes.html#cb92-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb92-5"><a href="análisis-con-datos-faltantes.html#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="fu">paste</span>(<span class="st">&quot;Outliers: &quot;</span>, <span class="fu">paste</span>(out, <span class="at">collapse =</span> <span class="st">&quot;, &quot;</span>)))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-65-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="percentiles" class="section level3" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Percentiles</h3>
<ul>
<li>Este método de detección de valores atípicos se basa en los percentiles. Con el método de los percentiles, todas las observaciones que se encuentren fuera del intervalo formado por los percentiles 2.5 y 97.5 se considerarán como posibles valores atípicos. También pueden considerarse otros percentiles, como el 1 y el 99, o el 5 y el 95, para construir el intervalo.</li>
</ul>
<p><span class="math display">\[
I=[q_{0.25}-1.5\cdot\textsf{IQR}; q_{0.75}+1.5\cdot\textsf{IQR}]
\]</span></p>
<ul>
<li>Los valores de los percentiles inferior y superior (y, por tanto, los límites inferior y superior del intervalo) pueden calcularse con la función <code>quantile()</code></li>
</ul>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="análisis-con-datos-faltantes.html#cb93-1" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="ot">&lt;-</span> <span class="fu">quantile</span>(dat<span class="sc">$</span>hwy, <span class="fl">0.025</span>)</span>
<span id="cb93-2"><a href="análisis-con-datos-faltantes.html#cb93-2" aria-hidden="true" tabindex="-1"></a>lower_bound</span></code></pre></div>
<pre><code>## 2.5% 
##   14</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="análisis-con-datos-faltantes.html#cb95-1" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="ot">&lt;-</span> <span class="fu">quantile</span>(dat<span class="sc">$</span>hwy, <span class="fl">0.975</span>)</span>
<span id="cb95-2"><a href="análisis-con-datos-faltantes.html#cb95-2" aria-hidden="true" tabindex="-1"></a>upper_bound</span></code></pre></div>
<pre><code>##  97.5% 
## 35.175</code></pre>
<ul>
<li>Según este método, todas las observaciones por debajo de 14 y por encima de 35.175 se considerarán posibles valores atípicos. Los números de fila de las observaciones fuera del intervalo pueden extraerse entonces con la función <code>which()</code></li>
</ul>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="análisis-con-datos-faltantes.html#cb97-1" aria-hidden="true" tabindex="-1"></a>outlier_ind <span class="ot">&lt;-</span> <span class="fu">which</span>(dat<span class="sc">$</span>hwy <span class="sc">&lt;</span> lower_bound <span class="sc">|</span> dat<span class="sc">$</span>hwy <span class="sc">&gt;</span> upper_bound)</span>
<span id="cb97-2"><a href="análisis-con-datos-faltantes.html#cb97-2" aria-hidden="true" tabindex="-1"></a>outlier_ind</span></code></pre></div>
<pre><code>##  [1]  55  60  66  70 106 107 127 197 213 222 223</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="análisis-con-datos-faltantes.html#cb99-1" aria-hidden="true" tabindex="-1"></a>dat[outlier_ind, <span class="st">&quot;hwy&quot;</span>]</span></code></pre></div>
<pre><code>## # A tibble: 11 x 1
##      hwy
##    &lt;int&gt;
##  1    12
##  2    12
##  3    12
##  4    12
##  5    36
##  6    36
##  7    12
##  8    37
##  9    44
## 10    44
## 11    41</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="análisis-con-datos-faltantes.html#cb101-1" aria-hidden="true" tabindex="-1"></a>dat[outlier_ind, ]</span></code></pre></div>
<pre><code>## # A tibble: 11 x 11
##    manufacturer model    displ  year   cyl trans  drv     cty   hwy fl    class 
##    &lt;chr&gt;        &lt;chr&gt;    &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 dodge        dakota ~   4.7  2008     8 auto(~ 4         9    12 e     pickup
##  2 dodge        durango~   4.7  2008     8 auto(~ 4         9    12 e     suv   
##  3 dodge        ram 150~   4.7  2008     8 auto(~ 4         9    12 e     pickup
##  4 dodge        ram 150~   4.7  2008     8 manua~ 4         9    12 e     pickup
##  5 honda        civic      1.8  2008     4 auto(~ f        25    36 r     subco~
##  6 honda        civic      1.8  2008     4 auto(~ f        24    36 c     subco~
##  7 jeep         grand c~   4.7  2008     8 auto(~ 4         9    12 e     suv   
##  8 toyota       corolla    1.8  2008     4 manua~ f        28    37 r     compa~
##  9 volkswagen   jetta      1.9  1999     4 manua~ f        33    44 d     compa~
## 10 volkswagen   new bee~   1.9  1999     4 manua~ f        35    44 d     subco~
## 11 volkswagen   new bee~   1.9  1999     4 auto(~ f        29    41 d     subco~</code></pre>
<ul>
<li>Hay 11 valores atípicos potenciales según el método de los percentiles. Para reducir este número, puede establecer los percentiles en 1 y 99:</li>
</ul>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="análisis-con-datos-faltantes.html#cb103-1" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="ot">&lt;-</span> <span class="fu">quantile</span>(dat<span class="sc">$</span>hwy, <span class="fl">0.01</span>)</span>
<span id="cb103-2"><a href="análisis-con-datos-faltantes.html#cb103-2" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="ot">&lt;-</span> <span class="fu">quantile</span>(dat<span class="sc">$</span>hwy, <span class="fl">0.99</span>)</span>
<span id="cb103-3"><a href="análisis-con-datos-faltantes.html#cb103-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-4"><a href="análisis-con-datos-faltantes.html#cb103-4" aria-hidden="true" tabindex="-1"></a>outlier_ind <span class="ot">&lt;-</span> <span class="fu">which</span>(dat<span class="sc">$</span>hwy <span class="sc">&lt;</span> lower_bound <span class="sc">|</span> dat<span class="sc">$</span>hwy <span class="sc">&gt;</span> upper_bound)</span>
<span id="cb103-5"><a href="análisis-con-datos-faltantes.html#cb103-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-6"><a href="análisis-con-datos-faltantes.html#cb103-6" aria-hidden="true" tabindex="-1"></a>dat[outlier_ind, ]</span></code></pre></div>
<pre><code>## # A tibble: 3 x 11
##   manufacturer model      displ  year   cyl trans  drv     cty   hwy fl    class
##   &lt;chr&gt;        &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt;
## 1 volkswagen   jetta        1.9  1999     4 manua~ f        33    44 d     comp~
## 2 volkswagen   new beetle   1.9  1999     4 manua~ f        35    44 d     subc~
## 3 volkswagen   new beetle   1.9  1999     4 auto(~ f        29    41 d     subc~</code></pre>
</div>
<div id="filtro-de-hampel" class="section level3" number="2.4.5">
<h3><span class="header-section-number">2.4.5</span> Filtro de Hampel</h3>
<ul>
<li>Otro método, conocido como <em>filtro de Hampel</em>, consiste en considerar como valores atípicos los valores fuera del intervalo formado por la mediana, más o menos 3 desviaciones absolutas de la mediana</li>
</ul>
<p><span class="math display">\[
I=[\tilde{X}-3\cdot\textsf{MAD}, \tilde{X}+3\cdot\textsf{MAD}],
\]</span>
donde <code>MAD</code> es la desviación absoluta de la mediana y se define como la mediana de las desviaciones absolutas de la mediana <span class="math inline">\(\tilde{X}=\textsf{median}(X)\)</span> de los datos</p>
<p><span class="math display">\[
\textsf{MAD}=\textsf{median}(|X_{i}-\tilde{X}|)
\]</span></p>
<ul>
<li>Para este método, primero establecemos los límites del intervalo, gracias a las funciones <code>median()</code> y <code>mad()</code></li>
</ul>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="análisis-con-datos-faltantes.html#cb105-1" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="ot">&lt;-</span> <span class="fu">median</span>(dat<span class="sc">$</span>hwy) <span class="sc">-</span> <span class="dv">3</span> <span class="sc">*</span> <span class="fu">mad</span>(dat<span class="sc">$</span>hwy, <span class="at">constant =</span> <span class="dv">1</span>)</span>
<span id="cb105-2"><a href="análisis-con-datos-faltantes.html#cb105-2" aria-hidden="true" tabindex="-1"></a>lower_bound</span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="análisis-con-datos-faltantes.html#cb107-1" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="ot">&lt;-</span> <span class="fu">median</span>(dat<span class="sc">$</span>hwy) <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> <span class="fu">mad</span>(dat<span class="sc">$</span>hwy, <span class="at">constant =</span> <span class="dv">1</span>)</span>
<span id="cb107-2"><a href="análisis-con-datos-faltantes.html#cb107-2" aria-hidden="true" tabindex="-1"></a>upper_bound</span></code></pre></div>
<pre><code>## [1] 39</code></pre>
<ul>
<li>Según este método, todas las observaciones por debajo de 9 y por encima de 39 se considerarán como posibles valores atípicos. Los números de fila de las observaciones que están fuera del intervalo pueden entonces extraerse con la función <code>which()</code>. Según el filtro de <code>Hampel</code>, hay 3 valores atípicos para la variable <code>hwy</code>.</li>
</ul>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="análisis-con-datos-faltantes.html#cb109-1" aria-hidden="true" tabindex="-1"></a>outlier_ind <span class="ot">&lt;-</span> <span class="fu">which</span>(dat<span class="sc">$</span>hwy <span class="sc">&lt;</span> lower_bound <span class="sc">|</span> dat<span class="sc">$</span>hwy <span class="sc">&gt;</span> upper_bound)</span>
<span id="cb109-2"><a href="análisis-con-datos-faltantes.html#cb109-2" aria-hidden="true" tabindex="-1"></a>outlier_ind</span></code></pre></div>
<pre><code>## [1] 213 222 223</code></pre>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="análisis-con-datos-faltantes.html#cb111-1" aria-hidden="true" tabindex="-1"></a>dat[outlier_ind, ]</span></code></pre></div>
<pre><code>## # A tibble: 3 x 11
##   manufacturer model      displ  year   cyl trans  drv     cty   hwy fl    class
##   &lt;chr&gt;        &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt;
## 1 volkswagen   jetta        1.9  1999     4 manua~ f        33    44 d     comp~
## 2 volkswagen   new beetle   1.9  1999     4 manua~ f        35    44 d     subc~
## 3 volkswagen   new beetle   1.9  1999     4 auto(~ f        29    41 d     subc~</code></pre>
</div>
<div id="prueba-de-grubbs" class="section level3" number="2.4.6">
<h3><span class="header-section-number">2.4.6</span> Prueba de Grubbs</h3>
<ul>
<li><p>La prueba de <code>Grubbs</code> permite detectar si el valor más alto o más bajo de un conjunto de datos es un valor atípico. La prueba de <code>Grubbs</code> detecta un valor atípico cada vez (valor más alto o más bajo), por lo que las hipótesis nula y alternativa son las siguientes</p>
<ul>
<li><span class="math inline">\(H_{0}\)</span>: El valor más alto/bajo no es un valor atípico</li>
<li><span class="math inline">\(H_{1}\)</span>: El valor más alto/bajo es un valor atípico</li>
</ul></li>
<li><p>Como para cualquier prueba estadística, si el valor <span class="math inline">\(p\)</span> es inferior al umbral de significación elegido (generalmente <span class="math inline">\(\alpha=0.05\)</span>), se rechaza la hipótesis nula y se concluye que el valor más bajo/más alto es un valor atípico. Por el contrario, si el valor <span class="math inline">\(p\)</span> es mayor o igual que el nivel de significación, no se rechaza la hipótesis nula y concluiremos que, basándonos en los datos, no rechazamos la hipótesis de que el valor más bajo/más alto no es un valor atípico. Tenga en cuenta que la prueba de <code>Grubbs</code> no es apropiada para un tamaño de muestra <span class="math inline">\(n\leq6\)</span>. Para realizar la prueba de <code>Grubbs</code> en <code>R</code>, utilizamos la función <code>grubbs.test()</code> del paquete <code>outliers</code></p></li>
</ul>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="análisis-con-datos-faltantes.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(outliers)</span>
<span id="cb113-2"><a href="análisis-con-datos-faltantes.html#cb113-2" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">grubbs.test</span>(dat<span class="sc">$</span>hwy)</span>
<span id="cb113-3"><a href="análisis-con-datos-faltantes.html#cb113-3" aria-hidden="true" tabindex="-1"></a>test</span></code></pre></div>
<pre><code>## 
##  Grubbs test for one outlier
## 
## data:  dat$hwy
## G = 3.45274, U = 0.94862, p-value = 0.05555
## alternative hypothesis: highest value 44 is an outlier</code></pre>
<ul>
<li>El valor <span class="math inline">\(p\)</span> es de 0.056. Al nivel de significación del 5%, no rechazamos la hipótesis de que el valor más alto 44 no es un valor atípico. No tenemos evidencia suficiente para decir que 44 es un valor atípico. Por defecto, la prueba se realiza sobre el valor más alto (como se muestra en la salida de <code>R</code>: hipótesis alternativa: el valor más alto 44 es un valor atípico). Si desea realizar la prueba para el valor más bajo, simplemente añada el argumento <code>opposite = TRUE</code> en la función <code>grubbs.test()</code></li>
</ul>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="análisis-con-datos-faltantes.html#cb115-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">grubbs.test</span>(dat<span class="sc">$</span>hwy, <span class="at">opposite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb115-2"><a href="análisis-con-datos-faltantes.html#cb115-2" aria-hidden="true" tabindex="-1"></a>test</span></code></pre></div>
<pre><code>## 
##  Grubbs test for one outlier
## 
## data:  dat$hwy
## G = 1.92122, U = 0.98409, p-value = 1
## alternative hypothesis: lowest value 12 is an outlier</code></pre>
<ul>
<li><p>La salida de <code>R</code> indica que la prueba se realiza ahora sobre el valor más bajo (véase la hipótesis alternativa: el valor más bajo 12 es un valor atípico). El valor <span class="math inline">\(p\)</span> es 1. Al nivel de significación del 5%, no rechazamos la hipótesis de que el valor más bajo 12 no es un valor atípico.</p></li>
<li><p>A modo de ilustración, sustituiremos ahora una observación por un valor más extremo y realizaremos la prueba de <code>Grubbs</code> en este nuevo conjunto de datos. Reemplacemos el <span class="math inline">\(34^{\text{th}}\)</span> por un valor de 212</p></li>
</ul>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="análisis-con-datos-faltantes.html#cb117-1" aria-hidden="true" tabindex="-1"></a>dat[<span class="dv">34</span>, <span class="st">&quot;hwy&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">212</span></span></code></pre></div>
<ul>
<li>Y ahora aplicamos la prueba de <code>Grubbs</code> para comprobar si el valor más alto es un valor atípico</li>
</ul>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="análisis-con-datos-faltantes.html#cb118-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">grubbs.test</span>(dat<span class="sc">$</span>hwy)</span>
<span id="cb118-2"><a href="análisis-con-datos-faltantes.html#cb118-2" aria-hidden="true" tabindex="-1"></a>test</span></code></pre></div>
<pre><code>## 
##  Grubbs test for one outlier
## 
## data:  dat$hwy
## G = 13.72240, U = 0.18836, p-value &lt; 2.2e-16
## alternative hypothesis: highest value 212 is an outlier</code></pre>
<ul>
<li>El valor <span class="math inline">\(p\)</span> es &lt; 0.001. Al nivel de significación del 5%, concluimos que el valor más alto 212 es un valor atípico.</li>
</ul>
</div>
<div id="prueba-de-dixon" class="section level3" number="2.4.7">
<h3><span class="header-section-number">2.4.7</span> Prueba de Dixon</h3>
<ul>
<li><p>Al igual que la prueba de <em>Grubbs</em>, la prueba de <em>Dixon</em> se utiliza para comprobar si un único valor bajo o alto es un valor atípico. Por lo tanto, si se sospecha que hay más de un valor atípico, la prueba tiene que realizarse en estos valores atípicos sospechosos individualmente.</p></li>
<li><p>Tenga en cuenta que la prueba de <code>Dixon</code> es más útil para muestras de pequeño tamaño (normalmente <span class="math inline">\(n\leq 25\)</span>). Para realizar la prueba de <code>Dixon</code> en <code>R</code>, utilizamos la función <code>dixon.test()</code> del paquete <code>outliers</code>. Sin embargo, restringimos nuestro conjunto de datos a las <code>20</code> primeras observaciones, ya que la prueba de <code>Dixon</code> sólo se puede realizar en muestras de pequeño tamaño (<code>R</code> arrojará un error y sólo acepta conjuntos de datos de 3 a 30 observaciones)</p></li>
</ul>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="análisis-con-datos-faltantes.html#cb120-1" aria-hidden="true" tabindex="-1"></a>subdat <span class="ot">&lt;-</span> dat[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>, ]</span>
<span id="cb120-2"><a href="análisis-con-datos-faltantes.html#cb120-2" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">dixon.test</span>(subdat<span class="sc">$</span>hwy)</span>
<span id="cb120-3"><a href="análisis-con-datos-faltantes.html#cb120-3" aria-hidden="true" tabindex="-1"></a>test</span></code></pre></div>
<pre><code>## 
##  Dixon test for outliers
## 
## data:  subdat$hwy
## Q = 0.57143, p-value = 0.006508
## alternative hypothesis: lowest value 15 is an outlier</code></pre>
<ul>
<li>Los resultados muestran que el valor más bajo, 15, es un valor atípico (valor <span class="math inline">\(p = 0.007\)</span>). Para comprobar el valor más alto, basta con añadir el argumento <code>opuesto = TRUE</code> a la función <code>dixon.test()</code></li>
</ul>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="análisis-con-datos-faltantes.html#cb122-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">dixon.test</span>(subdat<span class="sc">$</span>hwy, <span class="at">opposite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb122-2"><a href="análisis-con-datos-faltantes.html#cb122-2" aria-hidden="true" tabindex="-1"></a>test</span></code></pre></div>
<pre><code>## 
##  Dixon test for outliers
## 
## data:  subdat$hwy
## Q = 0.25, p-value = 0.8582
## alternative hypothesis: highest value 31 is an outlier</code></pre>
<ul>
<li>Los resultados muestran que el valor más alto 31 no es un valor atípico (valor <span class="math inline">\(p = 0.858\)</span>). Es una buena práctica comprobar siempre los resultados de la prueba estadística de valores atípicos con el diagrama de caja para asegurarse de que hemos comprobado todos los valores atípicos potenciales</li>
</ul>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="análisis-con-datos-faltantes.html#cb124-1" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">boxplot.stats</span>(subdat<span class="sc">$</span>hwy)<span class="sc">$</span>out</span>
<span id="cb124-2"><a href="análisis-con-datos-faltantes.html#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(subdat<span class="sc">$</span>hwy, <span class="at">ylab =</span> <span class="st">&quot;hwy&quot;</span>)</span>
<span id="cb124-3"><a href="análisis-con-datos-faltantes.html#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="fu">paste</span>(<span class="st">&quot;Outliers: &quot;</span>, <span class="fu">paste</span>(out, <span class="at">collapse =</span> <span class="st">&quot;, &quot;</span>)))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-82-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li>A partir del <code>boxplot</code>, vemos que también podríamos aplicar la prueba de <code>Dixon</code> sobre el valor 20 además del valor 15 realizado anteriormente. Esto puede hacerse encontrando el número de fila del valor mínimo, excluyendo este número de fila del conjunto de datos y aplicando finalmente la prueba de <code>Dixon</code> a este nuevo conjunto de datos</li>
</ul>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="análisis-con-datos-faltantes.html#cb125-1" aria-hidden="true" tabindex="-1"></a>remove_ind <span class="ot">&lt;-</span> <span class="fu">which.min</span>(subdat<span class="sc">$</span>hwy)</span>
<span id="cb125-2"><a href="análisis-con-datos-faltantes.html#cb125-2" aria-hidden="true" tabindex="-1"></a>subsubdat <span class="ot">&lt;-</span> subdat[<span class="sc">-</span>remove_ind, ]</span>
<span id="cb125-3"><a href="análisis-con-datos-faltantes.html#cb125-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-4"><a href="análisis-con-datos-faltantes.html#cb125-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(subsubdat)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 11
##   manufacturer model     displ  year   cyl trans   drv     cty   hwy fl    class
##   &lt;chr&gt;        &lt;chr&gt;     &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt;
## 1 audi         a4 quatt~   3.1  2008     6 auto(s~ 4        17    25 p     comp~
## 2 audi         a4 quatt~   3.1  2008     6 manual~ 4        15    25 p     comp~
## 3 audi         a6 quatt~   2.8  1999     6 auto(l~ 4        15    24 p     mids~
## 4 audi         a6 quatt~   3.1  2008     6 auto(s~ 4        17    25 p     mids~
## 5 audi         a6 quatt~   4.2  2008     8 auto(s~ 4        16    23 p     mids~
## 6 chevrolet    c1500 su~   5.3  2008     8 auto(l~ r        14    20 r     suv</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="análisis-con-datos-faltantes.html#cb127-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">dixon.test</span>(subsubdat<span class="sc">$</span>hwy)</span>
<span id="cb127-2"><a href="análisis-con-datos-faltantes.html#cb127-2" aria-hidden="true" tabindex="-1"></a>test</span></code></pre></div>
<pre><code>## 
##  Dixon test for outliers
## 
## data:  subsubdat$hwy
## Q = 0.44444, p-value = 0.1297
## alternative hypothesis: lowest value 20 is an outlier</code></pre>
<ul>
<li>Los resultados muestran que el segundo valor más bajo, 20, no es un valor atípico (valor <span class="math inline">\(p\)</span> = 0.13).</li>
</ul>
</div>
<div id="prueba-de-rosner" class="section level3" number="2.4.8">
<h3><span class="header-section-number">2.4.8</span> Prueba de Rosner</h3>
<ul>
<li><p>La prueba de <code>Rosner</code> para detectar valores atípicos tiene las siguientes ventajas. Se utiliza para detectar varios valores atípicos a la vez (a diferencia de la prueba de <code>Grubbs</code> y <code>Dixon</code>, que debe realizarse de forma iterativa para detectar múltiples valores atípicos), y está diseñado para evitar el problema del enmascaramiento, en el que un valor atípico cercano a otro atípico puede pasar desapercibido. A diferencia de la prueba de <code>Dixon</code>, hay que tener en cuenta que la prueba de <code>Rosner</code> es más apropiada cuando el tamaño de la muestra es grande (<span class="math inline">\(n\geq 20\)</span>). Por tanto, volvemos a utilizar el conjunto de datos inicial <code>dat</code>, que incluye 234 observaciones.</p></li>
<li><p>Para realizar la prueba de <code>Rosner</code> utilizamos la función <code>rosnerTest()</code> del paquete <code>EnvStats</code>. Esta función requiere al menos 2 argumentos: los datos y el número de presuntos valores atípicos <code>k</code> (con <code>k = 3</code> como número de presuntos valores atípicos por defecto). Para este ejemplo, establecemos que el número de presuntos valores atípicos sea igual a 3, tal y como sugiere el número de posibles valores atípicos esbozado en el <code>boxplot</code> al principio del artículo.</p></li>
</ul>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="análisis-con-datos-faltantes.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EnvStats)</span>
<span id="cb129-2"><a href="análisis-con-datos-faltantes.html#cb129-2" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">rosnerTest</span>(dat<span class="sc">$</span>hwy, <span class="at">k =</span> <span class="dv">3</span>)</span></code></pre></div>
<ul>
<li>Los resultados interesantes se ofrecen en la tabla <code>all.stats</code></li>
</ul>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="análisis-con-datos-faltantes.html#cb130-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>all.stats</span></code></pre></div>
<pre><code>##   i   Mean.i      SD.i Value Obs.Num     R.i+1 lambda.i+1 Outlier
## 1 0 24.21795 13.684345   212      34 13.722399   3.652091    TRUE
## 2 1 23.41202  5.951835    44     213  3.459098   3.650836   FALSE
## 3 2 23.32328  5.808172    44     222  3.559936   3.649575   FALSE</code></pre>
<ul>
<li>Basándonos en la prueba de <code>Rosner</code>, vemos que sólo hay un valor atípico (véase la columna de valores atípicos), y que es la observación <code>34</code> (véase <code>Obs.Num</code>) con un valor de <code>212</code> (véase <code>Value</code>).</li>
</ul>
</div>
<div id="tratamiento-de-los-valores-atípicos" class="section level3" number="2.4.9">
<h3><span class="header-section-number">2.4.9</span> Tratamiento de los valores atípicos</h3>
<ul>
<li><p>Una vez identificados los valores atípicos y habiendo decidido enmendar la situación según la naturaleza del problema, puede considerar uno de los siguientes enfoques.</p></li>
<li><p><strong>Imputación</strong></p>
<p>Este método se ha tratado en detalle en la discusión sobre el tratamiento de los valores faltantes.</p></li>
<li><p><strong>Capping</strong></p>
<p>Para los valores que se encuentran fuera de los límites de <span class="math inline">\(15\cdot\mathsf{IQR}\)</span>, podríamos poner un tope sustituyendo las observaciones que se encuentran fuera del límite inferior por el valor del <span class="math inline">\(5^{\textsf{th}}\)</span> percentile y las que se encuentran por encima del límite superior, por el valor del <span class="math inline">\(95^{\textsf{th}}\)</span> percentile. A continuación se muestra un código de ejemplo que logra esto</p></li>
</ul>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="análisis-con-datos-faltantes.html#cb132-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> dat<span class="sc">$</span>hwy</span>
<span id="cb132-2"><a href="análisis-con-datos-faltantes.html#cb132-2" aria-hidden="true" tabindex="-1"></a>qnt <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs=</span><span class="fu">c</span>(.<span class="dv">25</span>, .<span class="dv">75</span>), <span class="at">na.rm =</span> T)</span>
<span id="cb132-3"><a href="análisis-con-datos-faltantes.html#cb132-3" aria-hidden="true" tabindex="-1"></a>caps <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs=</span><span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">95</span>), <span class="at">na.rm =</span> T)</span></code></pre></div>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="análisis-con-datos-faltantes.html#cb133-1" aria-hidden="true" tabindex="-1"></a>H <span class="ot">&lt;-</span> <span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">IQR</span>(x, <span class="at">na.rm =</span> T)</span>
<span id="cb133-2"><a href="análisis-con-datos-faltantes.html#cb133-2" aria-hidden="true" tabindex="-1"></a>x[x <span class="sc">&lt;</span> (qnt[<span class="dv">1</span>] <span class="sc">-</span> H)] <span class="ot">&lt;-</span> caps[<span class="dv">1</span>]</span>
<span id="cb133-3"><a href="análisis-con-datos-faltantes.html#cb133-3" aria-hidden="true" tabindex="-1"></a>x[x <span class="sc">&gt;</span> (qnt[<span class="dv">2</span>] <span class="sc">+</span> H)] <span class="ot">&lt;-</span> caps[<span class="dv">2</span>]</span>
<span id="cb133-4"><a href="análisis-con-datos-faltantes.html#cb133-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(x)</span></code></pre></div>
<pre><code>## [1] 29 29 31 30 26 26</code></pre>
<ul>
<li><p><strong>Predicción</strong></p>
<p>En otro enfoque, los valores atípicos pueden sustituirse por valores perdidos <code>(NA)</code> y luego pueden predecirse considerándolos como una variable de respuesta. Ya hemos hablado de cómo predecir los valores perdidos en la sección anterior.</p></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introducción-a-postgresql-en-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/chapter1.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
